name: meditation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # flutter svg
  flutter_svg: ^2.2.3

  # go router
  go_router: ^17.0.1

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # flutter animate
  flutter_animate: ^4.5.2

  # bloc
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # get it
  get_it: ^9.2.0

  # logger
  logger: ^2.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
