name: meditation_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
    
  # Cupertino Icons
  cupertino_icons: ^1.0.8

  # flutter svg
  flutter_svg: ^2.2.3

  # go router
  go_router: ^17.0.1

  # hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # flutter animate
  flutter_animate: ^4.5.2

  # bloc
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # get it
  get_it: ^9.2.0

  # logger
  logger: ^2.6.2

  # cached_network_image
  cached_network_image: ^3.4.1

  # skeletonizer
  skeletonizer: ^2.1.2

  # url launcher
  url_launcher: ^6.3.2

  # connectivity_plus
  connectivity_plus: ^7.0.0

  # audio
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18

  # package info plus
  package_info_plus: ^9.0.0

  # lottie
  lottie: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # change app package name
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/jpg/
    - assets/lottie/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
